### ISSUE TITLE
Plugin doesn't appear in GPM

### ISSUE THREAD

**Issue by marshmn** [aaronhipple/grav-plugin-mailchimp#16]
It would be good if this plugin could be submitted for inclusion in GPM so that updates can automatically be picked up. It will also mean that more people are likely to find it in the first place and make it easier for them to get started with it.

**Comment by paulrudy** [comment]
Bumping this. @aaronhipple would you please consider submitting your plugin to the Grav GPM?

**Comment by aaronhipple** [comment]
Filed: getgrav/grav#2874

**Comment by aaronhipple** [comment]
Fixed by https://github.com/getgrav/grav/issues/2874#issuecomment-631668987
