### ISSUE TITLE
Error when no general list ID is set

### ISSUE THREAD

**Issue by JvanderCeelen** [aaronhipple/grav-plugin-mailchimp#23]
We used the plugin for a long time without setting a general list ID in the grav config. Instead we added a key to the form. After an update the plugin started throwing errors that the default list ID was given the value 'null'. So the list ID given via the form gets ignored and the list ID in the grav config isn't there, hence throwing an error.

**Comment by aaronhipple** [comment]
Thanks for filing @JvanderCeelen. Closing this as fixed by #22.
