### ISSUE TITLE
Possibly include vendor files

### ISSUE THREAD

**Issue by owlas** [aaronhipple/grav-plugin-mailchimp#5]
In order to get the plugin working I had to run the `composer.json` and get the vendor files. Following the approach of the standard grav plugins ([see here](https://github.com/getgrav/grav/issues/32)) it might be better to include the vendor files in the repo itself.

**Comment by aaronhipple** [comment]
It may be a necessary evil, but I really dislike the idea of tracking vendor dependencies in this repo. Do you happen to know, @owlas, if there was any further development along the lines indicated in [this comment](https://github.com/getgrav/grav/issues/32#issuecomment-53266732)? Specifically this paragraph:

> Alternatively you could leave all the composer vendor folders out of the repo, just commit the composer.json and create a bulild script to make your 100% self contained zip packages that are intended for distribution. This is probably the route we will go with for Grav in GitHub in the near future.

Setting up a proper automated build/release system feels like a more "right" solution to me, but I have to admit I've not been keeping up with developments in the Grav community as much as I should -- if it can't be done, it can't be done.

**Comment by MattAppleton** [comment]
Hi — very useful plugin idea! 


But - - I am getting a "Class 'DrewM\MailChimp\MailChimp' not found"  error even after I have installed what I think are the right files via composer. And the 'drewm' folder appears in the vendor folder.

Mind you this is all new to me.  Can we just get an example of what should be installed where for this to work?

thanks!

**Comment by OleVik** [comment]
Generally, it is best practice to ship non-compiled libraries - which Grav's extensions ostensibly are - _with_ vendor dependencies. Otherwise you are adding another layer of installation that requires dependencies themselves; Composer in this instance. For some cases, where there are a lot of tests or utilities, shipping only with the distributed files is preferred. This is more common with Node's NPM, but Composer also supports `--prefer-dist` for packages that use a /dist-folder.

A build-release system is possible, but generally for PHP it is unnecessary weight when scripts compile on run-time. For large vendor dependencies without /dist, use .gitignore to exclude unnecessary files. But being able to run the plugin directly after a `git clone` is beneficial, and for Grav common practice.

**Comment by ganar** [comment]
I agree with @OleVik here, @aaronhipple. This process of using composer to run the dependencies is too complex for the common user and it may not be feasible in a shared environment, if at all. 

Also important: the dependencies are being installed in the `/vendor` directory, in the root of the CMS, which makes it even harder to maintain GravCMS in the different environments. My very humble opinion is that this dependencies should be inside the plugin folder, in a separate `vendor` directory.

@aaronhipple are all of these necessary? Is this production code or test code? there are more that 5 thousand files in the dependencies: for instance `phpunit`

**Comment by aaronhipple** [comment]
Thanks for the feedback @ganar -- I'm a little curious about the number of dependencies you're seeing, as this plugin declares only two package dependencies (with a minimum PHP version also specified here):

https://github.com/aaronhipple/grav-plugin-mailchimp/blob/8c6d20d43132e070f4c68dada8fec4e9ae7aacee/composer.json#L15-L19

It's possible that in some configuration or another, one of those is bringing along its development dependencies (which include phpunit, among other things). I'd expect a typical installation not to do that, though.

Separate from all that, I have set up a build system for this project to produce archives containing vendor dependencies and attach them to releases, visible on the [Releases](https://github.com/aaronhipple/grav-plugin-mailchimp/releases) page. While it's not the solution asked for in this issue, they should provide an easier path to "drop-in" installation of the plugin.

In general my feelings about dependencies-in-version-control haven't changed — if anything, my current day-job workflow has moved even further away from that approach and as I'm only able to check in on and maintain this plugin sporadically, I'm hesitant to add another *different thing* to remember when I am able to come back to it.

**Comment by ganar** [comment]
> I'm a little curious about the number of dependencies you're seeing(…)
> It's possible that in some configuration or another, one of those is bringing along its development dependencies (…)

I did the following:

1. Did a clean installation of GravCMS
1. Installed _composer_ in order to install _grav-plugin-mailchimp_
1. Installed _grav-plugin-mailchimp_ using the instructions `composer require aaronhipple/grav-plugin-mailchimp
`
1. Compared the `/vendor` directory of my development machine with the one in the production server.

**Comment by aaronhipple** [comment]
Ah, yes, composer does do the dev dependencies by default in that scenario. `composer require aaronhipple/grav-plugin-mailchimp --update-no-dev` should install without incorporating those dev dependencies. I've updated the README to reflect this.

**Comment by ganar** [comment]
Yes! that is so much better:

````
composer require aaronhipple/grav-plugin-mailchimp --update-no-dev
Using version ^0.1.1 for aaronhipple/grav-plugin-mailchimp  
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies                                       
Package operations: 3 installs, 0 updates, 55 removals

  - Removing webmozart/assert (1.4.0)
  - Removing victorjonsson/markdowndocs (dev-master)
  - Removing theseer/tokenizer (1.1.2)
  - Removing symfony/finder (v4.2.8)
  - Removing symfony/dom-crawler (v4.2.8)
  - Removing symfony/css-selector (v4.2.8)
  - Removing symfony/browser-kit (v4.2.8)
  - Removing sebastian/version (2.0.1)
  - Removing sebastian/resource-operations (2.0.1)
  - Removing sebastian/recursion-context (3.0.0)
  - Removing sebastian/object-reflector (1.1.1)
  - Removing sebastian/object-enumerator (3.0.3)
  - Removing sebastian/global-state (2.0.0)
  - Removing sebastian/exporter (3.1.0)
  - Removing sebastian/environment (4.2.2)
  - Removing sebastian/diff (3.0.2)
  - Removing sebastian/comparator (3.0.2)
  - Removing sebastian/code-unit-reverse-lookup (1.0.1)
  - Removing phpunit/phpunit (7.5.11)
  - Removing phpunit/php-token-stream (3.0.1)
  - Removing phpunit/php-timer (2.1.1)
  - Removing phpunit/php-text-template (1.2.1)
  - Removing phpunit/php-file-iterator (2.0.2)
  - Removing phpunit/php-code-coverage (6.1.4)
  - Removing phpstan/phpstan-deprecation-rules (0.11)
  - Removing phpstan/phpstan (0.11.6)
  - Removing phpstan/phpdoc-parser (0.3.3)
  - Removing phpspec/prophecy (1.8.0)
  - Removing phpdocumentor/type-resolver (0.4.0)
  - Removing phpdocumentor/reflection-docblock (4.3.1)
  - Removing phpdocumentor/reflection-common (1.0.1)
  - Removing phar-io/version (2.0.1)
  - Removing phar-io/manifest (1.0.3)
  - Removing ocramius/package-versions (1.4.0)
  - Removing nikic/php-parser (v4.2.1)
  - Removing nette/utils (v3.0.1)
  - Removing nette/schema (v1.0.0)
  - Removing nette/robot-loader (v3.2.0)
  - Removing nette/php-generator (v3.2.2)
  - Removing nette/neon (v3.0.0)
  - Removing nette/finder (v2.5.0)
  - Removing nette/di (v3.0.0)
  - Removing nette/bootstrap (v3.0.0)
  - Removing myclabs/deep-copy (1.9.1)
  - Removing jean85/pretty-package-versions (1.2)
  - Removing guzzlehttp/promises (v1.3.1)
  - Removing guzzlehttp/guzzle (6.3.3)
  - Removing fzaninotto/faker (v1.8.0)
  - Removing facebook/webdriver (1.6.0)
  - Removing doctrine/instantiator (1.2.0)
  - Removing composer/xdebug-handler (1.3.2)
  - Removing codeception/stub (2.1.0)
  - Removing codeception/phpunit-wrapper (7.7.1)
  - Removing codeception/codeception (2.5.6)
  - Removing behat/gherkin (v4.6.0)
  - Installing composer/installers (v1.6.0): Loading from cache
  - Installing drewm/mailchimp-api (v2.5.3): Loading from cache
  - Installing aaronhipple/grav-plugin-mailchimp (v0.1.1): Downloading (100%)     
 
Writing lock file
Generating autoload files
````

**Comment by aaronhipple** [comment]
Calling this fixed by the CI/release setup and availability in gpm (see #16)
