### ISSUE TITLE
Installation instructions?

### ISSUE THREAD

**Issue by JunkMyFunk** [aaronhipple/grav-plugin-mailchimp#7]
Maybe I'm being a bit slow here, but how do I install this plugin? It's not listed in `bin/gpm index` and it's not available via `composer require` either. Some installation instructions wouldn't be amiss.

**Comment by aaronhipple** [comment]
I've added some quick and dirty instructions now that we're properly published on Packagist. `gpm` instructions will be pending some useful resolution to #5 -- I'll be digging on that further.
